In [1]:
import torch
from torch import nn

net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
X = torch.rand(size=(2, 4))
net(X)

tensor([[-0.1680],
        [-0.1432]], grad_fn=<AddmmBackward0>)

In [3]:
#接下来，我们创建了一个大小为(2, 4)的输入张量X，其中2表示批量大小，4表示每个样本的特征数。
# 然后，我们将输入张量X传递给网络模型net进行前向传播。
#在前向传播过程中，输入张量X经过第一个线性层和ReLU激活函数后，输出的形状变为(2, 8)。
# 然后，输出张量再经过第二个线性层，最终输出的形状变为(2, 1)。
#因此，输入(2, 4)的输出形状为(2, 1)。这是由于网络模型的结构和输入张量的形状决定的。

In [7]:
# 参数访问
# 如下所示，我们可以检查第二个全连接层的参数。该层包括权重和偏置。
print(net[2].state_dict())

OrderedDict([('weight', tensor([[-0.0164,  0.0645,  0.1885,  0.3104, -0.1807,  0.3301,  0.2976,  0.1144]])), ('bias', tensor([-0.1973]))])


In [11]:
# 通过名字来访问具体的参数
print(net[2].bias)
print(net[2].bias.data)

Parameter containing:
tensor([-0.1973], requires_grad=True)
tensor([-0.1973])


In [9]:
net[2].weight.grad == None

True

In [12]:
# 一次性访问所有参数
print(*[(name, param.shape) for name, param in net[0].named_parameters()])
print(*[(name, param.shape) for name, param in net.named_parameters()])

net.state_dict()['2.bias'].data

('weight', torch.Size([8, 4])) ('bias', torch.Size([8]))
('0.weight', torch.Size([8, 4])) ('0.bias', torch.Size([8])) ('2.weight', torch.Size([1, 8])) ('2.bias', torch.Size([1]))


tensor([-0.1973])